from pathlib import Path
from typing import Protocol

from ..domain.models import (DecisionLog, ProjectDescriptor, ProvisionedTarget, QCRun,
                             SourceAnalysis, WorkerResult, WorkerTask)


class RunStore(Protocol):
    def save_run(self, run: QCRun) -> None: ...
    def get_run(self, run_id: str) -> QCRun | None: ...
    def append_decision(self, decision: DecisionLog) -> None: ...
    def cancel_stale_runs(self, repository: str, new_head_sha: str) -> list[str]: ...
    def enqueue_run(self, run_id: str) -> None: ...
    def claim_next_run(self) -> str | None: ...
    def complete_queued_run(self, run_id: str) -> None: ...


class CheckPublisher(Protocol):
    async def create_check(self, run: QCRun) -> int | None: ...
    async def start_check(self, run: QCRun) -> None: ...
    async def complete_check(self, run: QCRun) -> None: ...


class SourceManager(Protocol):
    async def prepare(self, run: QCRun) -> Path: ...
    def cleanup(self, workspace: Path) -> None: ...


class WorkerRuntime(Protocol):
    def execute(self, task: WorkerTask, project: ProjectDescriptor, workspace: Path) -> WorkerResult: ...


class TargetProvisioner(Protocol):
    def provision(self, run: QCRun, analysis: SourceAnalysis,
                  workspace: Path) -> ProvisionedTarget: ...
    def cleanup(self, run_id: str) -> None: ...
